import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, BriefcaseBusiness, Building2, CheckCircle2, ClipboardList, FileSearch, MessageSquareText, ShieldCheck, UserRoundSearch, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/shared/logo";

const resources = [
  [BriefcaseBusiness, "Publicação de vagas", "Crie e gerencie oportunidades com as informações necessárias para apresentar cada posição aos candidatos."],
  [UserRoundSearch, "Gestão de candidatos", "Centralize as pessoas candidatas por vaga e acompanhe quem participa de cada processo seletivo."],
  [ClipboardList, "Pipeline de recrutamento", "Atualize o status das candidaturas e organize o andamento do processo de forma simples para o time de RH."],
  [FileSearch, "Análise de informações", "Consulte currículo, carta de apresentação e informações enviadas pelo candidato em um único ambiente."],
  [MessageSquareText, "Contato com candidatos", "Inicie conversas vinculadas às candidaturas e mantenha a comunicação organizada durante o processo."],
  [Building2, "Perfil institucional", "Apresente sua organização, identidade e informações relevantes para fortalecer sua presença junto aos talentos."],
] as const;

export default function CompanyRegistrationPage() {
  return <main className="min-h-screen bg-white text-slate-950">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Logo/><div className="flex items-center gap-3"><Link href="/" className="hidden items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900 sm:flex"><ArrowLeft className="h-4 w-4"/>Área de candidatos</Link><Button variant="outline" render={<Link href="/login?next=/dashboard/empresa"/>} nativeButton={false}>Entrar</Button></div></div></header>

    <section className="border-b border-slate-200 bg-[#f6f8fc]"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-24"><div className="self-center"><p className="text-sm font-semibold text-primary">JOBERA PARA EMPRESAS</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Recrutamento mais organizado para sua empresa</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Publique vagas, centralize candidaturas e acompanhe processos seletivos em um único ambiente. Uma experiência objetiva para RH, gestores e empresas que precisam contratar.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" render={<Link href="/login?next=/dashboard/empresa"/>} nativeButton={false}>Cadastrar minha empresa <ArrowRight className="ml-2 h-4 w-4"/></Button><Button size="lg" variant="outline" render={<Link href="/login?next=/dashboard/empresa"/>} nativeButton={false}>Já tenho acesso</Button></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-600">{["Área exclusiva para empresas","Gestão centralizada","Fluxo simples para o RH"].map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary"/>{x}</span>)}</div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-7 shadow-xl shadow-slate-200/50"><div className="flex items-center justify-between border-b border-slate-100 pb-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Visão geral</p><h2 className="mt-1 text-xl font-semibold">Painel de recrutamento</h2></div><BarChart3 className="h-6 w-6 text-primary"/></div><div className="mt-6 grid grid-cols-3 gap-3">{[["Vagas","12"],["Candidatos","148"],["Em processo","37"]].map(([a,b])=><div key={a} className="rounded-lg border border-slate-200 p-4"><p className="text-2xl font-bold">{b}</p><p className="mt-1 text-xs text-slate-500">{a}</p></div>)}</div><div className="mt-6 rounded-lg border border-slate-200"><p className="border-b border-slate-100 px-4 py-3 text-sm font-semibold">Processos recentes</p>{["Desenvolvedor(a) Front-end","Analista de Marketing","Assistente Administrativo"].map(x=><div key={x} className="flex items-center gap-3 border-b border-slate-100 px-4 py-3 last:border-0"><UsersRound className="h-4 w-4 text-slate-400"/><div className="flex-1"><p className="text-sm font-medium">{x}</p><p className="text-xs text-slate-500">Novas candidaturas recebidas</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-medium text-primary">Ativa</span></div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">RECRUTAMENTO E SELEÇÃO</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Recursos para organizar suas contratações</h2><p className="mt-4 leading-7 text-slate-600">Do anúncio da oportunidade ao acompanhamento dos candidatos, concentre as principais atividades do processo seletivo no Jobera.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{resources.map(([Icon,title,text])=><article key={title} className="bg-white p-7"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50 text-primary"><Icon className="h-5 w-5"/></div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section>

    <section className="bg-slate-950 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p className="text-sm font-semibold text-blue-300">PARA RH E GESTORES</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Menos informações dispersas. Mais clareza sobre cada contratação.</h2><p className="mt-5 max-w-xl leading-7 text-slate-300">Tenha uma visão única das vagas e pessoas candidatas, com informações organizadas para apoiar o acompanhamento do processo seletivo.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[UsersRound,"Central de candidatos"],[BarChart3,"Acompanhamento do processo"],[ShieldCheck,"Acesso empresarial"],[BriefcaseBusiness,"Gestão de oportunidades"]].map(([Icon,label])=>{const C=Icon as typeof UsersRound;return <div key={label as string} className="rounded-xl border border-white/10 bg-white/5 p-5"><C className="h-5 w-5 text-blue-300"/><p className="mt-3 font-medium">{label as string}</p></div>})}</div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="text-center"><p className="text-sm font-semibold text-primary">COMO FUNCIONA</p><h2 className="mt-3 text-3xl font-bold">Da publicação ao processo seletivo</h2></div><div className="mt-12 grid gap-8 md:grid-cols-4">{[["01","Cadastre sua empresa","Acesse com uma conta e vincule sua organização ao Jobera."],["02","Publique uma vaga","Cadastre a oportunidade com cargo, requisitos e demais informações."],["03","Receba candidatos","As candidaturas ficam organizadas e vinculadas à vaga correspondente."],["04","Conduza o processo","Analise perfis, atualize etapas e converse com candidatos."]].map(([n,t,d])=><div key={n}><span className="text-sm font-bold text-primary">{n}</span><h3 className="mt-3 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>)}</div></section>

    <section className="border-t border-slate-200 bg-[#f6f8fc]"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-4 py-14 sm:px-6 md:flex-row md:items-center lg:px-8"><div><h2 className="text-2xl font-bold">Sua próxima contratação pode começar aqui.</h2><p className="mt-2 text-slate-600">Cadastre sua organização e acesse a área empresarial do Jobera.</p></div><Button size="lg" render={<Link href="/login?next=/dashboard/empresa"/>} nativeButton={false}>Cadastrar minha empresa <ArrowRight className="ml-2 h-4 w-4"/></Button></div></section>
  </main>;
}
