import type { DiscoveryData } from "@/types/jobs";

export const MOCK_DISCOVERY: DiscoveryData = {
  summary: {
    analyzed: 12483,
    compatible: 183,
    veryCompatible: 27,
    perfect: 6,
  },
  filters: [
    { id: "f1", label: "Remoto" },
    { id: "f2", label: "CLT" },
    { id: "f3", label: "React" },
    { id: "f4", label: "Node" },
    { id: "f5", label: "Pleno" },
    { id: "f6", label: "Brasil" },
    { id: "f7", label: "AWS" },
  ],
  jobs: [
    {
      id: "1",
      company: "Nubank",
      role: "Engenheiro(a) Frontend Sênior",
      compatibility: 98,
      approvalProbability: {
        level: "alta",
        stars: 5,
        reasons: [
          "Poucos candidatos.",
          "Empresa costuma responder.",
          "Perfil muito parecido com os últimos contratados.",
          "Currículo excelente.",
          "GitHub atualizado.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "pass" },
            { id: "s3", label: "Técnico", status: "warning" },
          ],
          suggestion: "Treine Docker antes.",
        },
      },
      bestSendTime: {
        dayLabel: "Hoje",
        timeRange: "09:00–10:30",
        insight:
          "Empresas semelhantes respondem mais rápido nesse horário.",
      },
      salary: "R$ 18.000 – R$ 24.000",
      salaryMin: 18000,
      salaryMax: 24000,
      location: "Remoto · Brasil",
      logo: "Nu",
      color: "#8A05BE",
      href: "/dashboard/vagas/1",
      stack: ["React", "Next.js", "Node", "AWS", "Docker"],
      reasons: [
        { id: "r1", text: "React obrigatório", type: "match" },
        { id: "r2", text: "Você possui TypeScript", type: "match" },
        { id: "r3", text: "Empresa aceita remoto", type: "match" },
        { id: "r4", text: "Salário dentro do objetivo", type: "match" },
        { id: "r5", text: "Inglês compatível", type: "match" },
        { id: "r6", text: "Docker desejável", type: "warning" },
      ],
      stats: {
        responseDays: 4,
        processDays: 18,
        steps: 3,
        candidates: 32,
      },
      benefits: ["Stock options", "Plano de saúde", "Day off aniversário"],
      remote: true,
    },
    {
      id: "2",
      company: "Mercado Livre",
      role: "Engenheiro(a) de Software Sênior",
      compatibility: 96,
      approvalProbability: {
        level: "alta",
        stars: 4,
        reasons: [
          "Stack muito alinhada ao perfil.",
          "Empresa responde em até 5 dias.",
          "Processo estruturado e previsível.",
          "Experiência com e-commerce é plus.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "pass" },
            { id: "s3", label: "Técnico", status: "pass" },
            { id: "s4", label: "System Design", status: "warning" },
          ],
          suggestion: "Pratique system design de plataformas de alto volume.",
        },
      },
      bestSendTime: {
        dayLabel: "Amanhã",
        timeRange: "08:30–10:00",
        insight:
          "Recrutadores costumam revisar candidaturas neste intervalo.",
      },
      salary: "R$ 16.000 – R$ 22.000",
      salaryMin: 16000,
      salaryMax: 22000,
      location: "Remoto · Brasil",
      logo: "ML",
      color: "#FFE600",
      href: "/dashboard/vagas/2",
      stack: ["React", "TypeScript", "Node", "PostgreSQL", "AWS"],
      reasons: [
        { id: "r1", text: "Stack alinhada ao seu perfil", type: "match" },
        { id: "r2", text: "Experiência com e-commerce é plus", type: "match" },
        { id: "r3", text: "100% remoto", type: "match" },
        { id: "r4", text: "Salário dentro do objetivo", type: "match" },
        { id: "r5", text: "Inglês intermediário desejável", type: "warning" },
      ],
      stats: {
        responseDays: 5,
        processDays: 20,
        steps: 4,
        candidates: 41,
      },
      benefits: ["Stock options", "Plano de saúde", "Auxílio home office"],
      remote: true,
    },
    {
      id: "3",
      company: "iFood",
      role: "Desenvolvedor(a) Full Stack Pleno",
      compatibility: 95,
      approvalProbability: {
        level: "media",
        stars: 3,
        reasons: [
          "Muitos candidatos (67 est.).",
          "Kotlin é diferencial não presente.",
          "Modelo híbrido pode ser barreira.",
          "React e Node atendem bem.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "warning" },
            { id: "s3", label: "Técnico", status: "warning" },
          ],
          suggestion: "Revise conceitos de Kotlin e Kubernetes.",
        },
      },
      bestSendTime: {
        dayLabel: "Hoje",
        timeRange: "14:00–16:00",
        insight:
          "Empresas de food tech tendem a responder mais rápido à tarde.",
      },
      salary: "R$ 12.000 – R$ 16.000",
      salaryMin: 12000,
      salaryMax: 16000,
      location: "Híbrido · São Paulo",
      logo: "iF",
      color: "#EA1D2C",
      href: "/dashboard/vagas/3",
      stack: ["React", "Node.js", "Kotlin", "Docker", "Kubernetes"],
      reasons: [
        { id: "r1", text: "React e Node no core", type: "match" },
        { id: "r2", text: "Modelo híbrido aceito", type: "match" },
        { id: "r3", text: "Cultura de engenharia forte", type: "match" },
        { id: "r4", text: "Kotlin é diferencial", type: "warning" },
      ],
      stats: {
        responseDays: 3,
        processDays: 14,
        steps: 3,
        candidates: 67,
      },
      benefits: ["Vale refeição", "Gympass", "Licença parental estendida"],
      remote: false,
    },
    {
      id: "4",
      company: "Google",
      role: "Software Engineer — Frontend",
      compatibility: 94,
      approvalProbability: {
        level: "alta",
        stars: 4,
        reasons: [
          "React e TypeScript no core.",
          "Poucos candidatos qualificados.",
          "Processo bem estruturado.",
          "Empresa valoriza impacto em escala.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "pass" },
            { id: "s3", label: "Técnico", status: "pass" },
          ],
          suggestion: "Prepare algoritmos e system design de frontend.",
        },
      },
      bestSendTime: {
        dayLabel: "Segunda-feira",
        timeRange: "10:00–11:30",
        insight:
          "Empresas globais abrem a semana revisando candidaturas de engenharia.",
      },
      salary: "R$ 20.000 – R$ 28.000",
      salaryMin: 20000,
      salaryMax: 28000,
      location: "Remoto · Brasil",
      logo: "G",
      color: "#4285F4",
      href: "/dashboard/vagas/4",
      stack: ["React", "TypeScript", "Node", "GCP", "GraphQL"],
      reasons: [
        { id: "r1", text: "React é sua stack principal", type: "match" },
        { id: "r2", text: "Perfil técnico sólido", type: "match" },
        { id: "r3", text: "Remoto disponível", type: "match" },
        { id: "r4", text: "Inglês fluente necessário", type: "warning" },
      ],
      stats: {
        responseDays: 7,
        processDays: 24,
        steps: 4,
        candidates: 52,
      },
      benefits: ["Stock options", "Plano de saúde premium", "Licença parental"],
      remote: true,
    },
    {
      id: "5",
      company: "PicPay",
      role: "Desenvolvedor(a) Full Stack Pleno",
      compatibility: 94,
      approvalProbability: {
        level: "alta",
        stars: 4,
        reasons: [
          "Stack alinhada ao perfil.",
          "Empresa responde rápido.",
          "Processo enxuto.",
          "Experiência com fintech é plus.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "pass" },
            { id: "s3", label: "Técnico", status: "warning" },
          ],
          suggestion: "Revise conceitos de microsserviços e Kafka.",
        },
      },
      bestSendTime: {
        dayLabel: "Hoje",
        timeRange: "11:00–12:30",
        insight:
          "Fintechs costumam responder mais rápido no meio da manhã.",
      },
      salary: "R$ 11.000 – R$ 15.000",
      salaryMin: 11000,
      salaryMax: 15000,
      location: "Remoto · Brasil",
      logo: "PP",
      color: "#21C25E",
      href: "/dashboard/vagas/5",
      stack: ["React", "Node.js", "Kotlin", "Docker", "Kafka"],
      reasons: [
        { id: "r1", text: "React e Node no core", type: "match" },
        { id: "r2", text: "100% remoto", type: "match" },
        { id: "r3", text: "Cultura de engenharia forte", type: "match" },
        { id: "r4", text: "Kotlin é diferencial", type: "warning" },
      ],
      stats: {
        responseDays: 3,
        processDays: 15,
        steps: 3,
        candidates: 38,
      },
      benefits: ["Stock options", "Vale refeição", "Plano de saúde"],
      remote: true,
    },
  ],
  companies: [
    {
      id: "c1",
      name: "Nubank",
      logo: "Nu",
      color: "#8A05BE",
      compatibility: 98,
      environment: "Scale-up",
      remote: true,
      benefits: ["Stock options", "Saúde premium", "Remoto"],
      href: "/dashboard/empresas/nubank",
    },
    {
      id: "c2",
      name: "Mercado Livre",
      logo: "ML",
      color: "#FFE600",
      compatibility: 96,
      environment: "Corporativa",
      remote: true,
      benefits: ["Stock options", "Remoto", "Learning budget"],
      href: "/dashboard/empresas/mercadolivre",
    },
    {
      id: "c3",
      name: "iFood",
      logo: "iF",
      color: "#EA1D2C",
      compatibility: 95,
      environment: "Scale-up",
      remote: false,
      benefits: ["Vale refeição", "Gympass", "Plano de saúde"],
      href: "/dashboard/empresas/ifood",
    },
    {
      id: "c4",
      name: "Google",
      logo: "G",
      color: "#4285F4",
      compatibility: 94,
      environment: "Corporativa",
      remote: true,
      benefits: ["Stock options", "Saúde premium", "Remoto"],
      href: "/dashboard/empresas/google",
    },
    {
      id: "c5",
      name: "PicPay",
      logo: "PP",
      color: "#21C25E",
      compatibility: 94,
      environment: "Scale-up",
      remote: true,
      benefits: ["Stock options", "Flexibilidade", "Plano de saúde"],
      href: "/dashboard/empresas/picpay",
    },
  ],
  regions: [
    { id: "br", country: "Brasil", flag: "🇧🇷", count: 89, x: 32, y: 62 },
    { id: "us", country: "Estados Unidos", flag: "🇺🇸", count: 42, x: 22, y: 38 },
    { id: "ca", country: "Canadá", flag: "🇨🇦", count: 18, x: 24, y: 28 },
    { id: "pt", country: "Portugal", flag: "🇵🇹", count: 12, x: 46, y: 40 },
    { id: "de", country: "Alemanha", flag: "🇩🇪", count: 22, x: 52, y: 32 },
  ],
  salaryRadar: [
    { tech: "React", min: 8000, avg: 14500, max: 24000 },
    { tech: "Node", min: 9000, avg: 15200, max: 26000 },
    { tech: "Python", min: 8500, avg: 13800, max: 22000 },
    { tech: "Flutter", min: 7500, avg: 12000, max: 18000 },
    { tech: "Java", min: 9500, avg: 16000, max: 28000 },
  ],
  marketInsights: [
    { id: "m1", tech: "React", change: 8 },
    { id: "m2", tech: "Node", change: 14 },
    { id: "m3", tech: "Python", change: 21 },
    { id: "m4", tech: "AWS", change: 19 },
    { id: "m5", tech: "Docker", change: 11 },
  ],
  chat: [
    {
      id: "c1",
      role: "assistant",
      content:
        "Encontrei 5 vagas muito parecidas com seu perfil. A Nubank lidera o ranking com 98% de compatibilidade.",
      timestamp: "14:02",
    },
    {
      id: "c2",
      role: "user",
      content: "Sim, quero comparar salário e stack.",
      timestamp: "14:03",
    },
    {
      id: "c3",
      role: "assistant",
      content:
        "A Mercado Livre está em 2º com 96%, mas a Nubank tem processo 3 dias mais rápido. Posso abrir a comparação detalhada.",
      timestamp: "14:03",
    },
  ],
};

export const AI_SEARCH_EXAMPLES = [
  "Quero trabalhar remoto.",
  "Encontre vagas internacionais.",
  "Mostre empresas que contratam React.",
  "Quero ganhar acima de R$10.000.",
  "Aceito mudança de cidade.",
];

export const HIDE_REASONS = [
  { id: "distance" as const, label: "Muito longe" },
  { id: "salary" as const, label: "Salário baixo" },
  { id: "tech" as const, label: "Tecnologias" },
  { id: "company" as const, label: "Empresa" },
  { id: "other" as const, label: "Outro" },
];
