import type { DiscoveryData } from "@/types/jobs";

export const MOCK_DISCOVERY: DiscoveryData = {
  summary: {
    analyzed: 12483,
    compatible: 183,
    veryCompatible: 27,
    perfect: 6,
  },
  filters: [
    { id: "f1", label: "Remoto" },
    { id: "f2", label: "CLT" },
    { id: "f3", label: "React" },
    { id: "f4", label: "Node" },
    { id: "f5", label: "Pleno" },
    { id: "f6", label: "Brasil" },
    { id: "f7", label: "AWS" },
  ],
  jobs: [
    {
      id: "1",
      company: "Nubank",
      role: "Engenheiro(a) Frontend Sênior",
      compatibility: 97,
      approvalProbability: {
        level: "alta",
        stars: 5,
        reasons: [
          "Poucos candidatos.",
          "Empresa costuma responder.",
          "Perfil muito parecido com os últimos contratados.",
          "Currículo excelente.",
          "GitHub atualizado.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "pass" },
            { id: "s3", label: "Técnico", status: "warning" },
          ],
          suggestion: "Treine Docker antes.",
        },
      },
      bestSendTime: {
        dayLabel: "Hoje",
        timeRange: "09:00–10:30",
        insight:
          "Empresas semelhantes respondem mais rápido nesse horário.",
      },
      salary: "R$ 18.000 – R$ 24.000",
      salaryMin: 18000,
      salaryMax: 24000,
      location: "Remoto · Brasil",
      logo: "Nu",
      color: "#8A05BE",
      href: "/dashboard/vagas/1",
      stack: ["React", "Next.js", "Node", "AWS", "Docker"],
      reasons: [
        { id: "r1", text: "React obrigatório", type: "match" },
        { id: "r2", text: "Você possui TypeScript", type: "match" },
        { id: "r3", text: "Empresa aceita remoto", type: "match" },
        { id: "r4", text: "Salário dentro do objetivo", type: "match" },
        { id: "r5", text: "Inglês compatível", type: "match" },
        { id: "r6", text: "Docker desejável", type: "warning" },
      ],
      stats: {
        responseDays: 4,
        processDays: 18,
        steps: 3,
        candidates: 32,
      },
      benefits: ["Stock options", "Plano de saúde", "Day off aniversário"],
      remote: true,
    },
    {
      id: "2",
      company: "Stripe",
      role: "Software Engineer — Payments",
      compatibility: 94,
      approvalProbability: {
        level: "alta",
        stars: 4,
        reasons: [
          "Stack muito alinhada ao perfil.",
          "Empresa responde em até 6 dias.",
          "Processo estruturado e previsível.",
          "Experiência relevante com pagamentos.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "pass" },
            { id: "s3", label: "Técnico", status: "pass" },
            { id: "s4", label: "System Design", status: "warning" },
          ],
          suggestion: "Pratique system design de APIs de pagamento.",
        },
      },
      bestSendTime: {
        dayLabel: "Amanhã",
        timeRange: "08:30–10:00",
        insight:
          "Recrutadores internacionais costumam revisar candidaturas neste intervalo.",
      },
      salary: "US$ 140k – US$ 180k",
      salaryMin: 140000,
      salaryMax: 180000,
      location: "Remoto · Internacional",
      logo: "St",
      color: "#635BFF",
      href: "/dashboard/vagas/2",
      stack: ["React", "TypeScript", "Node", "PostgreSQL", "AWS"],
      reasons: [
        { id: "r1", text: "Stack alinhada ao seu perfil", type: "match" },
        { id: "r2", text: "Experiência com pagamentos é plus", type: "match" },
        { id: "r3", text: "100% remoto global", type: "match" },
        { id: "r4", text: "Salário acima do objetivo", type: "match" },
        { id: "r5", text: "Inglês fluente necessário", type: "warning" },
      ],
      stats: {
        responseDays: 6,
        processDays: 21,
        steps: 4,
        candidates: 48,
      },
      benefits: ["Equity", "Home office stipend", "4 semanas de férias"],
      remote: true,
    },
    {
      id: "3",
      company: "iFood",
      role: "Desenvolvedor(a) Full Stack Pleno",
      compatibility: 89,
      approvalProbability: {
        level: "media",
        stars: 3,
        reasons: [
          "Muitos candidatos (67 est.).",
          "Kotlin é diferencial não presente.",
          "Modelo híbrido pode ser barreira.",
          "React e Node atendem bem.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "warning" },
            { id: "s3", label: "Técnico", status: "warning" },
          ],
          suggestion: "Revise conceitos de Kotlin e Kubernetes.",
        },
      },
      bestSendTime: {
        dayLabel: "Hoje",
        timeRange: "14:00–16:00",
        insight:
          "Empresas de food tech tendem a responder mais rápido à tarde.",
      },
      salary: "R$ 12.000 – R$ 16.000",
      salaryMin: 12000,
      salaryMax: 16000,
      location: "Híbrido · São Paulo",
      logo: "iF",
      color: "#EA1D2C",
      href: "/dashboard/vagas/3",
      stack: ["React", "Node.js", "Kotlin", "Docker", "Kubernetes"],
      reasons: [
        { id: "r1", text: "React e Node no core", type: "match" },
        { id: "r2", text: "Modelo híbrido aceito", type: "match" },
        { id: "r3", text: "Cultura de engenharia forte", type: "match" },
        { id: "r4", text: "Kotlin é diferencial", type: "warning" },
      ],
      stats: {
        responseDays: 3,
        processDays: 14,
        steps: 3,
        candidates: 67,
      },
      benefits: ["Vale refeição", "Gympass", "Licença parental estendida"],
      remote: false,
    },
    {
      id: "4",
      company: "Vercel",
      role: "Developer Advocate — Next.js",
      compatibility: 91,
      approvalProbability: {
        level: "alta",
        stars: 4,
        reasons: [
          "Next.js é sua stack principal.",
          "Poucos candidatos qualificados.",
          "Open source alinhado ao perfil.",
          "Empresa valoriza conteúdo técnico.",
        ],
        simulation: {
          stages: [
            { id: "s1", label: "Triagem", status: "pass" },
            { id: "s2", label: "RH", status: "pass" },
            { id: "s3", label: "Técnico", status: "pass" },
          ],
          suggestion: "Prepare um talk ou artigo sobre Next.js.",
        },
      },
      bestSendTime: {
        dayLabel: "Segunda-feira",
        timeRange: "10:00–11:30",
        insight:
          "Startups globais abrem a semana revisando candidaturas de engenharia.",
      },
      salary: "US$ 120k – US$ 155k",
      salaryMin: 120000,
      salaryMax: 155000,
      location: "Remoto · Global",
      logo: "Ve",
      color: "#000000",
      href: "/dashboard/vagas/4",
      stack: ["Next.js", "React", "Edge", "TypeScript", "MDX"],
      reasons: [
        { id: "r1", text: "Next.js é sua stack principal", type: "match" },
        { id: "r2", text: "Perfil técnico + comunicação", type: "match" },
        { id: "r3", text: "Open source alinhado", type: "match" },
        { id: "r4", text: "Experiência em conteúdo técnico", type: "warning" },
      ],
      stats: {
        responseDays: 5,
        processDays: 16,
        steps: 3,
        candidates: 24,
      },
      benefits: ["Equity", "Conferências pagas", "Setup completo"],
      remote: true,
    },
  ],
  companies: [
    {
      id: "c1",
      name: "Nubank",
      logo: "Nu",
      color: "#8A05BE",
      compatibility: 96,
      environment: "Scale-up",
      remote: true,
      benefits: ["Stock options", "Saúde premium", "Remoto"],
      href: "/dashboard/empresas/nubank",
    },
    {
      id: "c2",
      name: "Stripe",
      logo: "St",
      color: "#635BFF",
      compatibility: 93,
      environment: "Corporativa",
      remote: true,
      benefits: ["Equity", "Global remote", "Learning budget"],
      href: "/dashboard/empresas/stripe",
    },
    {
      id: "c3",
      name: "QuintoAndar",
      logo: "QA",
      color: "#5063F0",
      compatibility: 88,
      environment: "Scale-up",
      remote: true,
      benefits: ["Auxílio home office", "Day off", "Plano de saúde"],
      href: "/dashboard/empresas/quintoandar",
    },
    {
      id: "c4",
      name: "Pipefy",
      logo: "Pi",
      color: "#3B82F6",
      compatibility: 85,
      environment: "Startup",
      remote: true,
      benefits: ["Flexibilidade", "Stock options", "Crescimento rápido"],
      href: "/dashboard/empresas/pipefy",
    },
  ],
  regions: [
    { id: "br", country: "Brasil", flag: "🇧🇷", count: 89, x: 32, y: 62 },
    { id: "us", country: "Estados Unidos", flag: "🇺🇸", count: 42, x: 22, y: 38 },
    { id: "ca", country: "Canadá", flag: "🇨🇦", count: 18, x: 24, y: 28 },
    { id: "pt", country: "Portugal", flag: "🇵🇹", count: 12, x: 46, y: 40 },
    { id: "de", country: "Alemanha", flag: "🇩🇪", count: 22, x: 52, y: 32 },
  ],
  salaryRadar: [
    { tech: "React", min: 8000, avg: 14500, max: 24000 },
    { tech: "Node", min: 9000, avg: 15200, max: 26000 },
    { tech: "Python", min: 8500, avg: 13800, max: 22000 },
    { tech: "Flutter", min: 7500, avg: 12000, max: 18000 },
    { tech: "Java", min: 9500, avg: 16000, max: 28000 },
  ],
  marketInsights: [
    { id: "m1", tech: "React", change: 8 },
    { id: "m2", tech: "Node", change: 14 },
    { id: "m3", tech: "Python", change: 21 },
    { id: "m4", tech: "AWS", change: 19 },
    { id: "m5", tech: "Docker", change: 11 },
  ],
  chat: [
    {
      id: "c1",
      role: "assistant",
      content:
        "Encontrei 4 vagas muito parecidas com seu perfil. Deseja comparar a Nubank com a Stripe?",
      timestamp: "14:02",
    },
    {
      id: "c2",
      role: "user",
      content: "Sim, quero comparar salário e stack.",
      timestamp: "14:03",
    },
    {
      id: "c3",
      role: "assistant",
      content:
        "A Stripe paga mais em dólar, mas a Nubank tem 97% de compatibilidade e processo 3 dias mais rápido. Posso abrir a comparação detalhada.",
      timestamp: "14:03",
    },
  ],
};

export const AI_SEARCH_EXAMPLES = [
  "Quero trabalhar remoto.",
  "Encontre vagas internacionais.",
  "Mostre empresas que contratam React.",
  "Quero ganhar acima de R$10.000.",
  "Aceito mudança de cidade.",
];

export const HIDE_REASONS = [
  { id: "distance" as const, label: "Muito longe" },
  { id: "salary" as const, label: "Salário baixo" },
  { id: "tech" as const, label: "Tecnologias" },
  { id: "company" as const, label: "Empresa" },
  { id: "other" as const, label: "Outro" },
];
