export const crudKeys = {
  applications: ["crud", "applications"] as const,
  notifications: ["crud", "notifications"] as const,
  chat: (context?: string) => ["crud", "chat", context ?? "all"] as const,
  timeline: (kind?: string) => ["crud", "timeline", kind ?? "all"] as const,
  goalChips: ["crud", "goal-chips"] as const,
  smartFilters: ["crud", "smart-filters"] as const,
  dailyMissions: ["crud", "daily-missions"] as const,
  employabilitySkills: ["crud", "employability-skills"] as const,
  employabilityOverview: ["crud", "employability-overview"] as const,
  hiddenJobs: ["crud", "hidden-jobs"] as const,
  favoriteCompanies: ["crud", "favorite-companies"] as const,
  resumeUploads: ["crud", "resume-uploads"] as const,
  oauthConnections: ["crud", "oauth-connections"] as const,
  experiences: ["crud", "experiences"] as const,
  skills: ["crud", "skills"] as const,
  languages: ["crud", "languages"] as const,
  certificates: ["crud", "certificates"] as const,
  education: ["crud", "education"] as const,
  courses: ["crud", "courses"] as const,
  projects: ["crud", "projects"] as const,
  profile: ["profile"] as const,
  profileVisibility: ["profile", "visibility"] as const,
  dashboard: ["dashboard"] as const,
  companyMemberships: ["company", "memberships"] as const,
  editableCompany: (companyId: string) =>
    ["company", "editable", companyId] as const,
  publicCompany: (slug: string) => ["company", "public", slug] as const,
};
