import {
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle2,
  Eye,
  FileText,
  FolderGit2,
  Globe2,
  LayoutDashboard,
  MessageSquare,
  Mic,
  Search,
  Settings,
  Sparkles,
  Target,
  TrendingUp,
  UserPlus,
  Video,
} from "lucide-react";
import type { DashboardData, NavItem } from "@/types/dashboard";

export const DASHBOARD_NAV_ITEMS: NavItem[] = [
  { label: "Copiloto", href: "/dashboard", icon: LayoutDashboard },
  { label: "Vagas", href: "/dashboard/vagas", icon: Briefcase, badge: 18 },
  { label: "Assistente IA", href: "/dashboard/assistente", icon: Sparkles },
  { label: "Currículo", href: "/dashboard/curriculo", icon: FileText },
  { label: "Portfólio", href: "/dashboard/portfolio", icon: Globe2 },
  { label: "Objetivos", href: "/dashboard/objetivos", icon: Target },
  { label: "Mercado", href: "/dashboard/mercado", icon: BarChart3 },
  { label: "Entrevistas", href: "/dashboard/entrevistas", icon: Mic, badge: 2 },
  { label: "Agenda", href: "/dashboard/agenda", icon: Calendar },
  { label: "Mensagens", href: "/dashboard/mensagens", icon: MessageSquare, badge: 3 },
  { label: "Empresas Favoritas", href: "/dashboard/empresas", icon: Building2 },
  { label: "Configurações", href: "/dashboard/configuracoes", icon: Settings },
];

export const SEARCH_EXAMPLES = [
  "Encontre vagas React.",
  "Como melhorar meu currículo?",
  "Quanto ganha um Tech Lead?",
  "Prepare-me para entrevista no Nubank.",
] as const;

export const MOCK_DASHBOARD: DashboardData = {
  user: {
    id: "usr_marcella",
    name: "Marcella Souza",
    firstName: "Marcella",
    email: "marcella@email.com",
    initials: "MS",
    plan: "Pro",
  },
  unreadNotifications: 4,
  unreadMessages: 3,
  timeline: [
    {
      id: "tl-1",
      time: "02:13",
      title: "Analisei 2.841 novas vagas",
      description: "Fontes: LinkedIn, Gupy, Greenhouse e 12 boards.",
      href: "/dashboard/vagas",
      icon: Search,
      color: "#4F7CFF",
      glow: "rgba(79,124,255,0.35)",
    },
    {
      id: "tl-2",
      time: "03:52",
      title: "Encontrei 18 compatíveis",
      description: "Score médio de 91% com o seu perfil.",
      href: "/dashboard/vagas",
      icon: CheckCircle2,
      color: "#22C55E",
      glow: "rgba(34,197,94,0.35)",
    },
    {
      id: "tl-3",
      time: "04:08",
      title: "Atualizei seu currículo para 6 vagas",
      description: "Versões otimizadas por ATS e palavras-chave.",
      href: "/dashboard/curriculo",
      icon: FileText,
      color: "#8B5CF6",
      glow: "rgba(139,92,246,0.35)",
    },
    {
      id: "tl-4",
      time: "04:15",
      title: "Candidatei você em 4 vagas autorizadas",
      description: "Candidaturas enviadas com carta personalizada.",
      href: "/dashboard/vagas",
      icon: Briefcase,
      color: "#F59E0B",
      glow: "rgba(245,158,11,0.35)",
    },
    {
      id: "tl-5",
      time: "06:22",
      title: "Empresa Nubank visualizou seu perfil",
      description: "Recruiter de Engineering abriu seu currículo.",
      href: "/dashboard/empresas",
      icon: Eye,
      color: "#820AD1",
      glow: "rgba(130,10,209,0.35)",
    },
    {
      id: "tl-6",
      time: "07:10",
      title: "Recebemos convite para entrevista",
      description: "iFood · Frontend React · amanhã às 14h.",
      href: "/dashboard/entrevistas",
      icon: Video,
      color: "#EC4899",
      glow: "rgba(236,72,153,0.35)",
    },
  ],
  kpis: [
    {
      id: "kpi-compat",
      label: "Compatibilidade média",
      value: 94,
      suffix: "%",
      delta: "+6%",
      deltaPositive: true,
      sparkline: [78, 82, 85, 84, 88, 91, 94],
      color: "#4F7CFF",
    },
    {
      id: "kpi-jobs",
      label: "Vagas encontradas hoje",
      value: 18,
      delta: "+7",
      deltaPositive: true,
      sparkline: [4, 8, 6, 11, 9, 14, 18],
      color: "#22C55E",
    },
    {
      id: "kpi-companies",
      label: "Empresas interessadas",
      value: 5,
      delta: "+2",
      deltaPositive: true,
      sparkline: [1, 1, 2, 2, 3, 4, 5],
      color: "#8B5CF6",
    },
    {
      id: "kpi-interviews",
      label: "Entrevistas",
      value: 2,
      delta: "+1",
      deltaPositive: true,
      sparkline: [0, 0, 1, 1, 1, 1, 2],
      color: "#F59E0B",
    },
    {
      id: "kpi-messages",
      label: "Mensagens",
      value: 3,
      delta: "2 novas",
      deltaPositive: true,
      sparkline: [0, 1, 1, 0, 2, 1, 3],
      color: "#EC4899",
    },
    {
      id: "kpi-evolution",
      label: "Compatibilidade evoluiu",
      value: 6,
      prefix: "+",
      suffix: "%",
      delta: "esta semana",
      deltaPositive: true,
      sparkline: [0, 1, 2, 3, 4, 5, 6],
      color: "#06B6D4",
    },
  ],
  recommendation: {
    id: "rec-1",
    title: "Sua maior oportunidade hoje",
    description:
      "Termine o treinamento de entrevista da empresa iFood. A IA detectou 87% de chance de avançar após o treino.",
    duration: "8 minutos",
    company: "iFood",
    ctaPrimary: "Iniciar treinamento",
    ctaSecondary: "Ignorar",
    href: "/dashboard/entrevistas/treino",
  },
  goal: {
    role: "Frontend React",
    location: "Remoto",
    salary: "R$8.000+",
    availability: "Imediata",
  },
  companies: [
    {
      id: "co-1",
      name: "Google",
      role: "Software Engineer",
      status: "Visualizou seu perfil",
      timeAgo: "há 2 horas",
      logo: "G",
      color: "#4285F4",
      href: "/dashboard/empresas/google",
    },
    {
      id: "co-2",
      name: "Nubank",
      role: "Frontend Engineer",
      status: "Abriu seu currículo",
      timeAgo: "há 4 horas",
      logo: "N",
      color: "#820AD1",
      href: "/dashboard/empresas/nubank",
    },
    {
      id: "co-3",
      name: "iFood",
      role: "React Developer",
      status: "Convidou para entrevista",
      timeAgo: "há 6 horas",
      logo: "i",
      color: "#EA1D2C",
      href: "/dashboard/empresas/ifood",
    },
    {
      id: "co-4",
      name: "Mercado Livre",
      role: "Frontend Sr.",
      status: "Salvou seu perfil",
      timeAgo: "há 1 dia",
      logo: "M",
      color: "#FFE600",
      href: "/dashboard/empresas/mercadolivre",
    },
  ],
  jobs: [
    {
      id: "job-1",
      company: "Nubank",
      role: "Frontend Engineer",
      compatibility: 97,
      salary: "R$12k–16k",
      location: "Remoto",
      logo: "N",
      color: "#820AD1",
      href: "/dashboard/vagas/1",
    },
    {
      id: "job-2",
      company: "iFood",
      role: "React Developer",
      compatibility: 94,
      salary: "R$10k–14k",
      location: "Híbrido · SP",
      logo: "i",
      color: "#EA1D2C",
      href: "/dashboard/vagas/2",
    },
    {
      id: "job-3",
      company: "Google",
      role: "Software Engineer",
      compatibility: 91,
      salary: "R$18k–25k",
      location: "Remoto",
      logo: "G",
      color: "#4285F4",
      href: "/dashboard/vagas/3",
    },
    {
      id: "job-4",
      company: "Spotify",
      role: "Frontend Engineer",
      compatibility: 89,
      salary: "R$14k–18k",
      location: "Remoto",
      logo: "S",
      color: "#1DB954",
      href: "/dashboard/vagas/4",
    },
    {
      id: "job-5",
      company: "Microsoft",
      role: "Full Stack React",
      compatibility: 88,
      salary: "R$15k–20k",
      location: "Remoto",
      logo: "M",
      color: "#00A4EF",
      href: "/dashboard/vagas/5",
    },
  ],
  market: [
    { id: "m-1", tech: "React", change: 8, demand: 92 },
    { id: "m-2", tech: "Node", change: 13, demand: 86 },
    { id: "m-3", tech: "Python", change: 21, demand: 95 },
    { id: "m-4", tech: "AWS", change: 18, demand: 88 },
    { id: "m-5", tech: "Docker", change: 12, demand: 79 },
  ],
  suggestions: [
    {
      id: "sug-1",
      title: "Aprenda Docker",
      description: "Sua compatibilidade aumenta 11% nas vagas senior.",
      impact: "+11% match",
      href: "/dashboard/assistente?q=docker",
      icon: TrendingUp,
      color: "#4F7CFF",
    },
    {
      id: "sug-2",
      title: "Atualize GitHub",
      description: "Mais 6 empresas analisam repositórios ativos.",
      impact: "+6 empresas",
      href: "/dashboard/portfolio",
      icon: FolderGit2,
      color: "#22C55E",
    },
    {
      id: "sug-3",
      title: "Adicione inglês B2",
      description: "Salário médio sobe R$2.100 no seu perfil.",
      impact: "+R$2.100",
      href: "/dashboard/curriculo",
      icon: UserPlus,
      color: "#F59E0B",
    },
  ],
  chat: [
    {
      id: "msg-1",
      role: "assistant",
      content:
        "Olá Marcella. Hoje encontrei uma vaga perfeita na Nubank com 97% de compatibilidade. Deseja ver?",
      timestamp: "07:42",
    },
  ],
  notifications: [
    {
      id: "n-1",
      title: "Convite de entrevista — iFood",
      description: "Frontend React · amanhã às 14:00",
      time: "07:10",
      group: "today",
      unread: true,
      actionLabel: "Confirmar",
      href: "/dashboard/entrevistas",
      icon: Video,
      color: "#EC4899",
    },
    {
      id: "n-2",
      title: "Nubank visualizou seu perfil",
      description: "Recruiter abriu seu currículo otimizado",
      time: "06:22",
      group: "today",
      unread: true,
      actionLabel: "Ver perfil",
      href: "/dashboard/empresas/nubank",
      icon: Eye,
      color: "#820AD1",
    },
    {
      id: "n-3",
      title: "4 candidaturas enviadas",
      description: "Com cartas personalizadas pela IA",
      time: "04:15",
      group: "today",
      unread: true,
      actionLabel: "Ver vagas",
      href: "/dashboard/vagas",
      icon: Briefcase,
      color: "#F59E0B",
    },
    {
      id: "n-4",
      title: "18 vagas compatíveis",
      description: "Score médio de 91%",
      time: "03:52",
      group: "today",
      unread: false,
      actionLabel: "Explorar",
      href: "/dashboard/vagas",
      icon: CheckCircle2,
      color: "#22C55E",
    },
    {
      id: "n-5",
      title: "Google salvou seu perfil",
      description: "Software Engineer · Remoto",
      time: "18:40",
      group: "yesterday",
      unread: false,
      actionLabel: "Ver detalhes",
      href: "/dashboard/empresas/google",
      icon: Building2,
      color: "#4285F4",
    },
    {
      id: "n-6",
      title: "Compatibilidade subiu +6%",
      description: "Seu perfil ficou mais competitivo",
      time: "Seg",
      group: "week",
      unread: false,
      actionLabel: "Ver evolução",
      href: "/dashboard",
      icon: TrendingUp,
      color: "#4F7CFF",
    },
  ],
};
