"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Plus, X, Trash2 } from "lucide-react";
import type { ExtractedProfile, Experience, Language, Project, Certificate } from "@/types/onboarding";
import { cn } from "@/lib/utils";

function Field({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean }) {
  const cls = "w-full rounded-xl border border-border bg-muted/40 px-3 py-2 text-sm text-foreground outline-none focus:border-primary/50 focus:ring-2 focus:ring-primary/20";
  return <label className="block space-y-1"><span className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">{label}</span>{multiline ? <textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} className={cls+" resize-y"}/> : <input value={value} onChange={e=>onChange(e.target.value)} className={cls}/>}</label>;
}
function Section({ title, onAdd, children }: { title: string; onAdd: () => void; children: React.ReactNode }) {
  return <div className="space-y-3"><div className="flex items-center justify-between"><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{title}</p><button type="button" onClick={onAdd} className="inline-flex items-center gap-1 rounded-lg border border-border px-2.5 py-1.5 text-xs text-foreground hover:bg-muted"><Plus className="h-3.5 w-3.5"/>Adicionar</button></div>{children}</div>;
}
export function SummaryCards({ profile, onChange, onContinue, className }: { profile: ExtractedProfile; onChange:(p:ExtractedProfile)=>void; onContinue:()=>void; className?:string }) {
  const [newSkill,setNewSkill]=useState("");
  const update=<K extends keyof ExtractedProfile>(key:K,value:ExtractedProfile[K])=>onChange({...profile,[key]:value});
  const addSkill=()=>{const skill=newSkill.trim();if(!skill)return;if(!profile.skills.some(s=>s.toLowerCase()===skill.toLowerCase()))update("skills",[...profile.skills,skill]);setNewSkill("");};
  const patchExperience=(i:number,patch:Partial<Experience>)=>update("experiences",profile.experiences.map((item,index)=>index===i?{...item,...patch}:item));
  const patchLanguage=(i:number,patch:Partial<Language>)=>update("languages",profile.languages.map((item,index)=>index===i?{...item,...patch}:item));
  const patchProject=(i:number,patch:Partial<Project>)=>update("projects",profile.projects.map((item,index)=>index===i?{...item,...patch}:item));
  const patchCertificate=(i:number,patch:Partial<Certificate>)=>update("certificates",profile.certificates.map((item,index)=>index===i?{...item,...patch}:item));
  const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;
  return <div className={cn("mx-auto w-full max-w-4xl space-y-6",className)}>
    <div className="space-y-2 text-center"><p className="text-sm font-medium text-primary">Encontramos</p><h2 className="text-3xl font-semibold text-foreground">Seu perfil preliminar</h2><p className="text-sm text-muted-foreground">Tudo abaixo é editável. Adicione, altere ou remova qualquer informação antes de continuar.</p></div>
    <motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="space-y-7 rounded-2xl border border-border bg-card/80 p-5 sm:p-7">
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Nome" value={profile.name} onChange={v=>{const initials=v.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()??"").join("");onChange({...profile,name:v,avatarInitials:initials});}}/><Field label="Cargo atual" value={profile.currentRole} onChange={v=>update("currentRole",v)}/><Field label="Senioridade" value={profile.seniority} onChange={v=>update("seniority",v)}/></div><Field label="Resumo" value={profile.summary} onChange={v=>update("summary",v)} multiline/>
      <Section title={`Competências (${profile.skills.length})`} onAdd={addSkill}><div className="flex flex-wrap gap-2">{profile.skills.map((skill,i)=><span key={`${skill}-${i}`} className="inline-flex items-center gap-1 rounded-full border border-primary/25 bg-primary/10 px-3 py-1 text-xs font-medium text-[#A8C0FF]">{skill}<button type="button" aria-label={`Remover ${skill}`} onClick={()=>update("skills",profile.skills.filter((_,x)=>x!==i))}><X className="h-3 w-3"/></button></span>)}</div><div className="flex gap-2"><input value={newSkill} onChange={e=>setNewSkill(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addSkill();}}} placeholder="Digite uma competência e pressione Enter" className="flex-1 rounded-xl border border-border bg-muted/40 px-3 py-2 text-sm outline-none focus:border-primary/50"/><button type="button" onClick={addSkill} className="rounded-xl bg-primary px-4 text-sm font-medium text-primary-foreground">Adicionar</button></div></Section>
      <Section title={`Experiências (${profile.experiences.length})`} onAdd={()=>update("experiences",[...profile.experiences,{id:id(),company:"",role:"",period:"",description:""}])}><div className="space-y-3">{profile.experiences.map((e,i)=><div key={e.id} className="relative grid gap-3 rounded-xl border border-border bg-muted/20 p-4 sm:grid-cols-2"><button type="button" onClick={()=>update("experiences",profile.experiences.filter((_,x)=>x!==i))} className="absolute right-3 top-3 text-muted-foreground hover:text-red-400"><Trash2 className="h-4 w-4"/></button><Field label="Cargo" value={e.role} onChange={v=>patchExperience(i,{role:v})}/><Field label="Empresa" value={e.company} onChange={v=>patchExperience(i,{company:v})}/><Field label="Período" value={e.period} onChange={v=>patchExperience(i,{period:v})}/><div className="sm:col-span-2"><Field label="Descrição" value={e.description} onChange={v=>patchExperience(i,{description:v})} multiline/></div></div>)}</div></Section>
      <Section title={`Idiomas (${profile.languages.length})`} onAdd={()=>update("languages",[...profile.languages,{id:id(),name:"",level:""}])}><div className="space-y-2">{profile.languages.map((l,i)=><div key={l.id} className="grid gap-2 rounded-xl border border-border bg-muted/20 p-3 sm:grid-cols-[1fr_1fr_auto]"><Field label="Idioma" value={l.name} onChange={v=>patchLanguage(i,{name:v})}/><Field label="Nível" value={l.level} onChange={v=>patchLanguage(i,{level:v})}/><button type="button" onClick={()=>update("languages",profile.languages.filter((_,x)=>x!==i))} className="self-end p-2 text-muted-foreground hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div>)}</div></Section>
      <Section title={`Projetos (${profile.projects.length})`} onAdd={()=>update("projects",[...profile.projects,{id:id(),name:"",description:"",tech:[]}])}><div className="space-y-3">{profile.projects.map((p,i)=><div key={p.id} className="relative space-y-3 rounded-xl border border-border bg-muted/20 p-4"><button type="button" onClick={()=>update("projects",profile.projects.filter((_,x)=>x!==i))} className="absolute right-3 top-3 text-muted-foreground hover:text-red-400"><Trash2 className="h-4 w-4"/></button><Field label="Projeto" value={p.name} onChange={v=>patchProject(i,{name:v})}/><Field label="Descrição" value={p.description} onChange={v=>patchProject(i,{description:v})} multiline/><Field label="Tecnologias (separadas por vírgula)" value={p.tech.join(", ")} onChange={v=>patchProject(i,{tech:v.split(",").map(x=>x.trim()).filter(Boolean)})}/></div>)}</div></Section>
      <Section title={`Certificados (${profile.certificates.length})`} onAdd={()=>update("certificates",[...profile.certificates,{id:id(),name:"",issuer:"",year:""}])}><div className="space-y-2">{profile.certificates.map((c,i)=><div key={c.id} className="grid gap-2 rounded-xl border border-border bg-muted/20 p-3 sm:grid-cols-[2fr_1.5fr_1fr_auto]"><Field label="Certificado" value={c.name} onChange={v=>patchCertificate(i,{name:v})}/><Field label="Instituição" value={c.issuer} onChange={v=>patchCertificate(i,{issuer:v})}/><Field label="Ano" value={c.year} onChange={v=>patchCertificate(i,{year:v})}/><button type="button" onClick={()=>update("certificates",profile.certificates.filter((_,x)=>x!==i))} className="self-end p-2 text-muted-foreground hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div>)}</div></Section>
    </motion.div><div className="flex justify-center"><button type="button" onClick={onContinue} className="inline-flex h-12 min-w-[220px] items-center justify-center rounded-xl bg-primary px-8 text-sm font-semibold text-primary-foreground">Salvar e continuar</button></div>
  </div>;
}
